name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: run pwd
        run: pwd

      - name: run ls
        run: ls
  
      - name: build the docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/webapp:latest
      
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: dockerwebapp21.azurecr.io
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_PASSWORD }}

      - name: Tag and Push Docker image to Azure Container Registry
        run: |
          docker tag webapp dockerwebapp21.azurecr.io/webapp:latest
          docker push dockerwebapp21.azurecr.io/webapp:latest
        env:
          DOCKER_BUILDKIT: 1  # Enable BuildKit for advanced build features
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}
          app-name: wa-webapp20240419220123-test
          images: dockerwebapp21.azurecr.io/webapp:latest
          multi-container-config-type: "compose"
          # If you have a specific docker-compose file, provide the path
        env:
          AZURE_WEBAPP_CONTAINER_WORKER_TYPE: "compose"
