name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: run pwd
        run: pwd

      - name: run ls
        run: ls
  
      - name: build the docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/webapp:latest
      
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: dockerwebapp21.azurecr.io
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_PASSWORD }}

      # - name: Tag and Push Docker image to Azure Container Registry
      #   run: |
      #     docker image ls
      #     docker tag webapp dockerwebapp21.azurecr.io/webapp:latest
      #     docker push dockerwebapp21.azurecr.io/webapp:latest
      - name: Tag and Push Docker image to Azure Container Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: dockerwebapp21.azurecr.io/rest-api:latest
        env:
          DOCKER_BUILDKIT: 1  # Enable BuildKit for advanced build features
      # - name: Deploy to Azure Web App
      #   uses: azure/webapps-deploy@v2
      #   with:
      #     publish-profile: ${{ secrets.PUBLISH_PROFILE }}
      #     app-name: wa-webapp20240419220123-test
      #     images: dockerwebapp21.azurecr.io/webapp:latest
      #     multi-container-config-type: "compose"
      #     # If you have a specific docker-compose file, provide the path
      #   env:
      #     AZURE_WEBAPP_CONTAINER_WORKER_TYPE: "compose"
  deploy:
      runs-on: ubuntu-latest
      needs: build
      environment:
        name: 'Production'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      permissions:
        id-token: write #This is required for requesting the JWT
  
      steps:
        # - name: Download artifact from build job
        #   uses: actions/download-artifact@v3
        #   with:
        #     name: .net-app
        
        - name: Login to Azure
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6035052AD1614DCE93B98F2483BF7149 }}
            tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0CAD580B770344A0907515EF87626DD7 }}
            subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AEE3CAB3D95640369BE419CE6DD5B47C }}
  
        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: 'webapp20240419220123'
            slot-name: 'Production'
            package: .
